### ISSUE TITLE
Latest version (1.2.11) fails to detect SIMD (UMD version)

### ISSUE THREAD

**Issue by phsultan** [GoogleChromeLabs/wasm-feature-detect#45] opened 2021-05-25 10:44 UTC
Hi all,

It looks like the currently available version from UMD at https://unpkg.com/wasm-feature-detect/dist/umd/index.js fails to detect SIMD.

### To reproduce
- enable WebAssembly SIMD support for Chrome 90 (in chrome://flags)
- go to https://unpkg.com/wasm-feature-detect/dist/umd/index.js (will redirect to https://unpkg.com/wasm-feature-detect@1.2.11/dist/umd/index.js))
- copy/paste the output to the JS console
- run `wasmFeatureDetect.simd().then(res => { console.log(res); })` => logs `false`

The previous version at https://unpkg.com/wasm-feature-detect@1.2.10/dist/umd/index.js logs `true` as expected.

Let me know if I missed something, thanks for the great work!

**Comment by surma** [comment] 2021-05-25 11:22
This is sadly working as intended. 

The SIMD proposal had op-code changes, and Chrome 90 only supports the _old_ SIMD. [Chrome 91 goes stable _today_](https://chromestatus.com/features/schedule) and we fixed wasm-feature-detect for that. See #43.

Gonna close this, but feel free to re-open if there are any further issues on this.

**Closed as completed by surma** 2021-05-25 11:22 UTC

**Comment by phsultan** [comment] 2021-05-25 11:33
Thanks a lot for your detailed answer. 👍
